name: edgeaispectrophotometer
include:
- /var/lib/arduino-app-cli/assets/0.12.0/services/arduino/llamacpp/service_compose.unoq.yaml
services:
  main:
    image: ghcr.io/arduino/app-bricks/python-apps-base:0.12.0
    depends_on:
      llamacpp-models-runner:
        condition: service_started
    volumes:
    - type: bind
      source: /home/arduino/ArduinoApps/edgeaispectrophotometer
      target: /app
    - type: bind
      source: /dev
      target: /dev
    - type: bind
      source: /run/udev
      target: /run/udev
      read_only: true
    - type: bind
      source: /run/user/1000/pipewire-0
      target: /run/user/1000/pipewire-0
    - type: bind
      source: /run/arduino-router.sock
      target: /run/arduino-router.sock
    - type: bind
      source: /run/arduino-cloud-connector
      target: /run/arduino-cloud-connector
    - type: bind
      source: /dev/leds/builtin/led1_b
      target: /dev/leds/builtin/led1_b
    - type: bind
      source: /dev/leds/builtin/led1_g
      target: /dev/leds/builtin/led1_g
    - type: bind
      source: /dev/leds/builtin/led1_r
      target: /dev/leds/builtin/led1_r
    - type: bind
      source: /dev/leds/builtin/led2_b
      target: /dev/leds/builtin/led2_b
    - type: bind
      source: /dev/leds/builtin/led2_g
      target: /dev/leds/builtin/led2_g
    - type: bind
      source: /dev/leds/builtin/led2_r
      target: /dev/leds/builtin/led2_r
    device_cgroup_rules:
    - c 226:* rmw
    - c 250:* rmw
    - c 504:* rmw
    - c 81:* rmw
    - c 116:* rmw
    ports:
    - 7000:7000
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    entrypoint: /run.sh
    extra_hosts:
    - msgpack-rpc-router:host-gateway
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.main: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/edgeaispectrophotometer
    environment:
      APP_HOME: /home/arduino/ArduinoApps/edgeaispectrophotometer
      BOARD_NAME: unoq
      HOST_IP: 192.168.0.16
      MODELS_PATH: /var/lib/arduino-app-cli/models
      XDG_RUNTIME_DIR: /run/user/1000
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
