services:
  llamacpp-models-runner:
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/edgeaispectrophotometer
    environment:
      APP_HOME: /home/arduino/ArduinoApps/edgeaispectrophotometer
      BOARD_NAME: unoq
      HOST_IP: 192.168.0.16
      MODELS_PATH: /var/lib/arduino-app-cli/models
